### ISSUE TITLE
How to accomplish non-fullscreen?

### ISSUE THREAD

**Issue by dylansproule** [jepiqueau/vue-videoplayer-app-starter#1]
Seems like CSS overrides aren't working?

Is this possible for the app?

**Comment by jepiqueau** [comment]
@dylansproule the plugin is fullscreen only.

**Comment by dylansproule** [comment]
Interesting as when you hit esc you not in full screen

**Comment by jepiqueau** [comment]
@dylansproule i assume you mean in the We.b version

**Comment by dylansproule** [comment]
yes this was the web version

**Comment by dylansproule** [comment]
What needs to be changed from not full screen?

**Comment by jepiqueau** [comment]
@dylansproule for Web only look at ionic/angular-app-starter there is an embedded mode for video

**Comment by jepiqueau** [comment]
@dylansproule hope this has help you. As i do not get news i close the issue
